# This file was generated by GoReleaser. DO NOT EDIT.
class Chilly < Formula
  desc "Have you got the chillys?"
  homepage ""
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/plumming/chilly/releases/download/0.0.9/chilly-darwin-amd64.tar.gz"
    sha256 "da099b7ab7a6c6e028cc07fbef63aa432e5431562af94e78428a2b4d480b7523"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/plumming/chilly/releases/download/0.0.9/chilly-linux-amd64.tar.gz"
      sha256 "de3356c551b83bca1955bc9e6c48fc964d40f1de541259db6735ab1e38da5474"
    end
  end

  def install
    bin.install "chilly"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
