# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dx < Formula
  desc "Have you got the chillys?"
  homepage ""
  version "0.0.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/plumming/dx/releases/download/0.0.19/dx-darwin-amd64.tar.gz"
    sha256 "6b646f2c6afb6ae0ba55c1b2ea4275023b175f43bf20e5fa2b8213d4bcfb1c51"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/plumming/dx/releases/download/0.0.19/dx-linux-amd64.tar.gz"
    sha256 "01ad2924f7c8f8983551b1f63d9153e43db7fd74cb2b56e28b808ddcadb9748c"
  end

  def install
    bin.install "dx"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
