# This file was generated by GoReleaser. DO NOT EDIT.
class Dx < Formula
  desc "Have you got the chillys?"
  homepage ""
  version "0.0.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/plumming/dx/releases/download/0.0.12/dx-darwin-amd64.tar.gz"
    sha256 "644cbb7c707ee8417f20fe814b417e6ffb9e4a31961216a48eb6cd937003db09"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/plumming/dx/releases/download/0.0.12/dx-linux-amd64.tar.gz"
      sha256 "a517dd065b0be2c1cae11486948c18ff8b440bdb33d7d9b910f739c4374470dd"
    end
  end

  def install
    bin.install "dx"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
